
name: 'deploy-k8s-action'
description: 'Action to deploy application on Kubernetes clusters'
inputs:
  k8s-cluster:
    description: 'Kubernetes cluster address'
    required: true
  k8s-token:
    description: 'Kubernetes token'
    required: true
  deployment-name:
    description: 'K8s deployment name'
    required: true
  environment:
    description: 'Environment like prod, production, preprod and etc'
    required: true
  namespace:
    description: 'Kubernetes cluster namespace'
    required: true
  version:
    description: 'Image version'
    required: false
    default: 'latest'
  container-registry-host:
    description: 'Image container registry host'
    required: false
  skip-rollout-check:
    description: 'Set true if deployment does not require a rollout status check'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        K8S_CLUSTER: ${{ inputs.k8s-cluster }}
        K8S_TOKEN: ${{ inputs.k8s-token }}
        DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        ENVIRONMENT: ${{ inputs.environment }}
        NAMESPACE: ${{ inputs.namespace }}
        VERSION: ${{ inputs.version }}
        CONTAINER_REGISTRY_HOST: ${{ inputs.container-registry-host }}
        SKIP_ROLLOUT_CHECK: ${{ inputs.skip-rollout-check }}
    - uses: actions/checkout@main

